services:

  auth_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: bookstore
      POSTGRES_DB: bookstore
    ports:
      - "54321:5432"
    networks:
      - bookstore
    volumes:
      - auth_data:/var/lib/postgresql/data

  book_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: bookstore
      POSTGRES_DB: bookstore
    ports:
      - "54323:5432"
    networks:
      - bookstore
    volumes:
      - book_data:/var/lib/postgresql/data

  book_cache:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - bookstore

  auth:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - bookstore
    depends_on:
      - auth_db

  book:
    build:
      context: ./book-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - bookstore
    depends_on:
      - book_db
      - book_cache
    command: "npm run dev"
    environment:
      DATABASE_URL: "postgres://postgres:bookstore@book_db:5432/bookstore"
      CACHE_TIMEOUT: 3600
      REDIS_HOST: book_cache
      REDIS_PORT: 6379

volumes:
  auth_data:
  book_data:

networks:
  bookstore:
    driver: bridge
